### ISSUE TITLE
libb4hvinscanner.so file is not found for few system architectures

### ISSUE THREAD

**Issue by udayasril** [bees4honey/mobile_vin_scanner#11]
libb4hvinscanner.so file is not found for few architectures. e.g., for arm64-v8a architecture I did not find .so file hence library is not supported for devices like Galaxy S6 Edge+.

**Comment by anumolu-l** [comment]
I am also facing same issues , great if you can provide libb4hvinscanner.so for arm64-v8a  and mips architecture.
