### ISSUE TITLE
Using B4H in React Native application causes linker command to fail with exit code 1

### ISSUE THREAD

**Issue by evanmrose** [bees4honey/mobile_vin_scanner#12]
(B4HCameraOverlayViewController.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by evanmrose** [comment]
@nik123 Any ideas here?

**Comment by nik123** [comment]
VIN Scanner library currently doesn't support bitcode technology. We're considering to enable bitcode in the nearest future but for now you may just disable bitcode in your project since it's still optional. To disable bitcode check out this thread on StackOverflow: http://stackoverflow.com/questions/31527343/app-store-team-error-saying-your-app-contains-bitcode-after-application-submis

**Comment by evanmrose** [comment]
Thanks for getting back to me @nik123 I disabled bitcode and that unleashed the dogs of hell unfortunately.

38 errors in the libB4HVINScanner.a file culminating in "ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

I'm trying to build to an iPhone 6 running iOS 9.2. Architectures is set to 'Standard Architectures'. 

Logs included below. 

`Undefined symbols for architecture arm64:
  "std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const", referenced from:
      b4hscanner::LuminanceSource::operator std::string() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BitMatrix::description() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GridSampler::checkAndNudgePoints(b4hscanner::Ref<b4hscanner::BitMatrix>, std::vector<float, std::allocator<float> >&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GF256Polynom::description() const in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::datamatrix::DecodedBitStreamParser::decode(b4hscanner::ArrayRef<unsigned char>) in libB4HVINScanner.a(dm_scanner.o)
  "std::ostream& std::ostream::_M_insert<double>(double)", referenced from:
      b4hscanner::operator<<(std::ostream&, b4hscanner::PerspectiveTransform const&) in libB4HVINScanner.a(dm_scanner.o)
  "std::ostream& std::ostream::_M_insert<unsigned long>(unsigned long)", referenced from:
      b4hscanner::operator<<(std::ostream&, b4hscanner::Result&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::operator<<(std::ostream&, b4hscanner::GF256Polynom const&) in libB4HVINScanner.a(dm_scanner.o)
  "std::ostream::operator<<(int)", referenced from:
      b4hscanner::GridSampler::checkAndNudgePoints(b4hscanner::Ref<b4hscanner::BitMatrix>, std::vector<float, std::allocator<float> >&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::operator<<(std::ostream&, b4hscanner::GF256 const&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::operator<<(std::ostream&, b4hscanner::GF256Polynom const&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::datamatrix::DecodedBitStreamParser::decodeAsciiSegment(b4hscanner::Ref<b4hscanner::BitSource>, std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >&, std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >&) in libB4HVINScanner.a(dm_scanner.o)
  "std::string::_Rep::_M_destroy(std::allocator<char> const&)", referenced from:
      b4hscanner::Exception::~Exception() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BitMatrix::description() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GridSampler::checkAndNudgePoints(b4hscanner::Ref<b4hscanner::BitMatrix>, std::vector<float, std::allocator<float> >&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GF256Polynom::description() const in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::datamatrix::DecodedBitStreamParser::decode(b4hscanner::ArrayRef<unsigned char>) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::DecoderResult::~DecoderResult() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::DecoderResult::~DecoderResult() in libB4HVINScanner.a(dm_scanner.o)
      ...
  "std::string::_Rep::_S_terminal", referenced from:
      char* std::string::_S_construct<char*>(char*, char*, std::allocator<char> const&, std::forward_iterator_tag) in libB4HVINScanner.a(dm_scanner.o)
  "std::string::_Rep::_S_empty_rep_storage", referenced from:
      b4hscanner::Exception::Exception() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::Exception::Exception() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::Exception::~Exception() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::FormatException::FormatException() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::ReaderException::ReaderException() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::FormatException::FormatException() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::ReaderException::ReaderException() in libB4HVINScanner.a(dm_scanner.o)
      ...
  "std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&)", referenced from:
      char* std::string::_S_construct<char*>(char*, char*, std::allocator<char> const&, std::forward_iterator_tag) in libB4HVINScanner.a(dm_scanner.o)
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)", referenced from:
      b4hscanner::Exception::Exception(char const*) in libB4HVINScanner.a(dm_scanner.o)
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)", referenced from:
      b4hscanner::DecoderResult::DecoderResult(b4hscanner::ArrayRef<unsigned char>, b4hscanner::Ref<b4hscanner::String>, b4hscanner::ArrayRef<b4hscanner::ArrayRef<unsigned char> >&, std::string const&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GlobalHistogramBinarizer::getBlackRow(int, b4hscanner::Ref<b4hscanner::BitArray>) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::String::String(std::string const&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::String::String(std::string const&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::datamatrix::DecodedBitStreamParser::decode(b4hscanner::ArrayRef<unsigned char>) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::datamatrix::Decoder::correctErrors(b4hscanner::ArrayRef<unsigned char>, int) in libB4HVINScanner.a(dm_scanner.o)
  "std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode)", referenced from:
      b4hscanner::LuminanceSource::operator std::string() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BitMatrix::description() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GridSampler::checkAndNudgePoints(b4hscanner::Ref<b4hscanner::BitMatrix>, std::vector<float, std::allocator<float> >&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GF256Polynom::description() const in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::datamatrix::DecodedBitStreamParser::decode(b4hscanner::ArrayRef<unsigned char>) in libB4HVINScanner.a(dm_scanner.o)
  "std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()", referenced from:
      b4hscanner::LuminanceSource::operator std::string() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BitMatrix::description() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GridSampler::checkAndNudgePoints(b4hscanner::Ref<b4hscanner::BitMatrix>, std::vector<float, std::allocator<float> >&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GF256Polynom::description() const in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::datamatrix::DecodedBitStreamParser::decode(b4hscanner::ArrayRef<unsigned char>) in libB4HVINScanner.a(dm_scanner.o)
  "std::ios_base::~ios_base()", referenced from:
      b4hscanner::LuminanceSource::operator std::string() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BitMatrix::description() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GridSampler::checkAndNudgePoints(b4hscanner::Ref<b4hscanner::BitMatrix>, std::vector<float, std::allocator<float> >&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GF256Polynom::description() const in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::datamatrix::DecodedBitStreamParser::decode(b4hscanner::ArrayRef<unsigned char>) in libB4HVINScanner.a(dm_scanner.o)
  "std::exception::~exception()", referenced from:
      b4hscanner::Exception::Exception(char const*) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::Exception::~Exception() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GlobalHistogramBinarizer::getBlackRow(int, b4hscanner::Ref<b4hscanner::BitArray>) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::datamatrix::Decoder::correctErrors(b4hscanner::ArrayRef<unsigned char>, int) in libB4HVINScanner.a(dm_scanner.o)
  "std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)", referenced from:
      b4hscanner::LuminanceSource::operator std::string() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::operator<<(std::ostream&, b4hscanner::Result&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::operator<<(std::ostream&, b4hscanner::BitMatrix const&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GridSampler::checkAndNudgePoints(b4hscanner::Ref<b4hscanner::BitMatrix>, std::vector<float, std::allocator<float> >&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::operator<<(std::ostream&, b4hscanner::PerspectiveTransform const&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::operator<<(std::ostream&, b4hscanner::String const&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::operator<<(std::ostream&, b4hscanner::GF256 const&) in libB4HVINScanner.a(dm_scanner.o)
      ...
  "std::__throw_bad_alloc()", referenced from:
      std::vector<unsigned int, std::allocator<unsigned int> >::operator=(std::vector<unsigned int, std::allocator<unsigned int> > const&) in libB4HVINScanner.a(dm_scanner.o)
      std::_Vector_base<b4hscanner::Ref<b4hscanner::datamatrix::PointsWithTransitions>, std::allocator<b4hscanner::Ref<b4hscanner::datamatrix::PointsWithTransitions> > >::_Vector_base(unsigned long, std::allocator<b4hscanner::Ref<b4hscanner::datamatrix::PointsWithTransitions> > const&) in libB4HVINScanner.a(dm_scanner.o)
      std::_Vector_base<b4hscanner::Ref<b4hscanner::datamatrix::DataBlock>, std::allocator<b4hscanner::Ref<b4hscanner::datamatrix::DataBlock> > >::_Vector_base(unsigned long, std::allocator<b4hscanner::Ref<b4hscanner::datamatrix::DataBlock> > const&) in libB4HVINScanner.a(dm_scanner.o)
      std::_Vector_base<b4hscanner::datamatrix::ECB*, std::allocator<b4hscanner::datamatrix::ECB*> >::_Vector_base(unsigned long, std::allocator<b4hscanner::datamatrix::ECB*> const&) in libB4HVINScanner.a(dm_scanner.o)
      std::vector<b4hscanner::Ref<b4hscanner::datamatrix::Version>, std::allocator<b4hscanner::Ref<b4hscanner::datamatrix::Version> > >::_M_insert_aux(__gnu_cxx::__normal_iterator<b4hscanner::Ref<b4hscanner::datamatrix::Version>*, std::vector<b4hscanner::Ref<b4hscanner::datamatrix::Version>, std::allocator<b4hscanner::Ref<b4hscanner::datamatrix::Version> > > >, b4hscanner::Ref<b4hscanner::datamatrix::Version> const&) in libB4HVINScanner.a(dm_scanner.o)
      std::vector<b4hscanner::datamatrix::ECB*, std::allocator<b4hscanner::datamatrix::ECB*> >::_M_insert_aux(__gnu_cxx::__normal_iterator<b4hscanner::datamatrix::ECB**, std::vector<b4hscanner::datamatrix::ECB*, std::allocator<b4hscanner::datamatrix::ECB*> > >, b4hscanner::datamatrix::ECB* const&) in libB4HVINScanner.a(dm_scanner.o)
      std::_Vector_base<b4hscanner::Ref<b4hscanner::GF256Polynom>, std::allocator<b4hscanner::Ref<b4hscanner::GF256Polynom> > >::_Vector_base(unsigned long, std::allocator<b4hscanner::Ref<b4hscanner::GF256Polynom> > const&) in libB4HVINScanner.a(dm_scanner.o)
      ...
  "std::__throw_logic_error(char const*)", referenced from:
      char* std::string::_S_construct<char*>(char*, char*, std::allocator<char> const&, std::forward_iterator_tag) in libB4HVINScanner.a(dm_scanner.o)
  "std::__throw_length_error(char const*)", referenced from:
      std::vector<b4hscanner::Ref<b4hscanner::datamatrix::Version>, std::allocator<b4hscanner::Ref<b4hscanner::datamatrix::Version> > >::_M_insert_aux(__gnu_cxx::__normal_iterator<b4hscanner::Ref<b4hscanner::datamatrix::Version>*, std::vector<b4hscanner::Ref<b4hscanner::datamatrix::Version>, std::allocator<b4hscanner::Ref<b4hscanner::datamatrix::Version> > > >, b4hscanner::Ref<b4hscanner::datamatrix::Version> const&) in libB4HVINScanner.a(dm_scanner.o)
      std::vector<b4hscanner::datamatrix::ECB*, std::allocator<b4hscanner::datamatrix::ECB*> >::_M_insert_aux(__gnu_cxx::__normal_iterator<b4hscanner::datamatrix::ECB**, std::vector<b4hscanner::datamatrix::ECB*, std::allocator<b4hscanner::datamatrix::ECB*> > >, b4hscanner::datamatrix::ECB* const&) in libB4HVINScanner.a(dm_scanner.o)
      std::vector<b4hscanner::Ref<b4hscanner::Reader>, std::allocator<b4hscanner::Ref<b4hscanner::Reader> > >::_M_insert_aux(__gnu_cxx::__normal_iterator<b4hscanner::Ref<b4hscanner::Reader>*, std::vector<b4hscanner::Ref<b4hscanner::Reader>, std::allocator<b4hscanner::Ref<b4hscanner::Reader> > > >, b4hscanner::Ref<b4hscanner::Reader> const&) in libB4HVINScanner.a(dm_scanner.o)
  "std::terminate()", referenced from:
      ___clang_call_terminate in libB4HVINScanner.a(DatamatrixWrapper.o)
      ___clang_call_terminate in libB4HVINScanner.a(dm_scanner.o)
  "typeinfo for std::exception", referenced from:
      typeinfo for b4hscanner::Exception in libB4HVINScanner.a(dm_scanner.o)
  "typeinfo for int", referenced from:
      b4hscanner::Counted::release() in libB4HVINScanner.a(DatamatrixWrapper.o)
      b4hscanner::Counted::release() in libB4HVINScanner.a(dm_scanner.o)
  "VTT for std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >", referenced from:
      b4hscanner::LuminanceSource::operator std::string() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BitMatrix::description() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GridSampler::checkAndNudgePoints(b4hscanner::Ref<b4hscanner::BitMatrix>, std::vector<float, std::allocator<float> >&) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GF256Polynom::description() const in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::datamatrix::DecodedBitStreamParser::decode(b4hscanner::ArrayRef<unsigned char>) in libB4HVINScanner.a(dm_scanner.o)
  "vtable for __cxxabiv1::__class_type_info", referenced from:
      typeinfo for b4hscanner::Counted in libB4HVINScanner.a(dm_scanner.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for __cxxabiv1::__pointer_type_info", referenced from:
      typeinfo for b4hscanner::ReaderException* in libB4HVINScanner.a(DatamatrixWrapper.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for __cxxabiv1::__si_class_type_info", referenced from:
      typeinfo for b4hscanner::Exception in libB4HVINScanner.a(dm_scanner.o)
      typeinfo for b4hscanner::ReaderException in libB4HVINScanner.a(dm_scanner.o)
      typeinfo for b4hscanner::NotFoundException in libB4HVINScanner.a(dm_scanner.o)
      typeinfo for b4hscanner::IllegalArgumentException in libB4HVINScanner.a(dm_scanner.o)
      typeinfo for b4hscanner::FormatException in libB4HVINScanner.a(dm_scanner.o)
      typeinfo for b4hscanner::ReedSolomonException in libB4HVINScanner.a(dm_scanner.o)
      typeinfo for b4hscanner::Reader in libB4HVINScanner.a(dm_scanner.o)
      ...
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "operator delete[](void*)", referenced from:
      b4hscanner::LuminanceSource::operator std::string() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BitMatrix::~BitMatrix() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BitMatrix::~BitMatrix() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BitMatrix::~BitMatrix() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GlobalHistogramBinarizer::getBlackRow(int, b4hscanner::Ref<b4hscanner::BitArray>) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GreyscaleLuminanceSource::~GreyscaleLuminanceSource() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GreyscaleLuminanceSource::~GreyscaleLuminanceSource() in libB4HVINScanner.a(dm_scanner.o)
      ...
  "operator delete(void*)", referenced from:
      -[DatamatrixWrapper getLuminanceSourceFromBuffer:imageBytes:] in libB4HVINScanner.a(DatamatrixWrapper.o)
      -[DatamatrixWrapper decode:withHints:] in libB4HVINScanner.a(DatamatrixWrapper.o)
      b4hscanner::Binarizer::~Binarizer() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BinaryBitmap::~BinaryBitmap() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BinaryBitmap::crop(int, int, int, int) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BinaryBitmap::rotateCounterClockwise() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BinaryBitmap::invert() in libB4HVINScanner.a(dm_scanner.o)
      ...
  "operator new[](unsigned long)", referenced from:
      b4hscanner::BitMatrix::BitMatrix(unsigned long) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BitMatrix::BitMatrix(unsigned long, unsigned long) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GlobalHistogramBinarizer::getBlackRow(int, b4hscanner::Ref<b4hscanner::BitArray>) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GreyscaleLuminanceSource::getRow(int, unsigned char*) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GreyscaleLuminanceSource::getMatrix() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GreyscaleRotatedLuminanceSource::getRow(int, unsigned char*) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GreyscaleRotatedLuminanceSource::getMatrix() in libB4HVINScanner.a(dm_scanner.o)
      ...
  "operator new(unsigned long)", referenced from:
      -[DatamatrixWrapper getLuminanceSourceFromBuffer:imageBytes:] in libB4HVINScanner.a(DatamatrixWrapper.o)
      -[DatamatrixWrapper decode:withHints:] in libB4HVINScanner.a(DatamatrixWrapper.o)
      b4hscanner::BinaryBitmap::crop(int, int, int, int) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BinaryBitmap::rotateCounterClockwise() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BinaryBitmap::invert() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::MultiFormatReader::setHints(b4hscanner::DecodeHints) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BitMatrix::getRow(int, b4hscanner::Ref<b4hscanner::BitArray>) in libB4HVINScanner.a(dm_scanner.o)
      ...
  "___cxa_allocate_exception", referenced from:
      -[DatamatrixWrapper getLuminanceSourceFromBuffer:imageBytes:] in libB4HVINScanner.a(DatamatrixWrapper.o)
      b4hscanner::Counted::release() in libB4HVINScanner.a(DatamatrixWrapper.o)
      b4hscanner::DecodeHints::addFormat(b4hscanner::BarcodeFormat) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::DecodeHints::containsFormat(b4hscanner::BarcodeFormat) const in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::LuminanceSource::crop(int, int, int, int) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::LuminanceSource::invert() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::LuminanceSource::rotateCounterClockwise() in libB4HVINScanner.a(dm_scanner.o)
      ...
  "___cxa_begin_catch", referenced from:
      -[DatamatrixWrapper decode:withHints:] in libB4HVINScanner.a(DatamatrixWrapper.o)
      ___clang_call_terminate in libB4HVINScanner.a(DatamatrixWrapper.o)
      b4hscanner::MultiFormatReader::decodeInternal(b4hscanner::Ref<b4hscanner::BinaryBitmap>) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GlobalHistogramBinarizer::getBlackRow(int, b4hscanner::Ref<b4hscanner::BitArray>) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::datamatrix::Decoder::correctErrors(b4hscanner::ArrayRef<unsigned char>, int) in libB4HVINScanner.a(dm_scanner.o)
      ___clang_call_terminate in libB4HVINScanner.a(dm_scanner.o)
  "___cxa_call_unexpected", referenced from:
      b4hscanner::ReedSolomonException::ReedSolomonException(char const*) in libB4HVINScanner.a(dm_scanner.o)
  "___cxa_end_catch", referenced from:
      -[DatamatrixWrapper decode:withHints:] in libB4HVINScanner.a(DatamatrixWrapper.o)
      b4hscanner::MultiFormatReader::decodeInternal(b4hscanner::Ref<b4hscanner::BinaryBitmap>) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::GlobalHistogramBinarizer::getBlackRow(int, b4hscanner::Ref<b4hscanner::BitArray>) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::datamatrix::Decoder::correctErrors(b4hscanner::ArrayRef<unsigned char>, int) in libB4HVINScanner.a(dm_scanner.o)
  "___cxa_free_exception", referenced from:
      -[DatamatrixWrapper getLuminanceSourceFromBuffer:imageBytes:] in libB4HVINScanner.a(DatamatrixWrapper.o)
      b4hscanner::DecodeHints::addFormat(b4hscanner::BarcodeFormat) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::DecodeHints::containsFormat(b4hscanner::BarcodeFormat) const in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::LuminanceSource::crop(int, int, int, int) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::LuminanceSource::invert() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::LuminanceSource::rotateCounterClockwise() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::MultiFormatReader::decodeInternal(b4hscanner::Ref<b4hscanner::BinaryBitmap>) in libB4HVINScanner.a(dm_scanner.o)
      ...
  "___cxa_pure_virtual", referenced from:
      vtable for b4hscanner::Binarizer in libB4HVINScanner.a(dm_scanner.o)
      vtable for b4hscanner::LuminanceSource in libB4HVINScanner.a(dm_scanner.o)
      vtable for b4hscanner::Reader in libB4HVINScanner.a(dm_scanner.o)
  "___cxa_throw", referenced from:
      -[DatamatrixWrapper getLuminanceSourceFromBuffer:imageBytes:] in libB4HVINScanner.a(DatamatrixWrapper.o)
      b4hscanner::Counted::release() in libB4HVINScanner.a(DatamatrixWrapper.o)
      b4hscanner::DecodeHints::addFormat(b4hscanner::BarcodeFormat) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::DecodeHints::containsFormat(b4hscanner::BarcodeFormat) const in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::LuminanceSource::crop(int, int, int, int) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::LuminanceSource::invert() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::LuminanceSource::rotateCounterClockwise() in libB4HVINScanner.a(dm_scanner.o)
      ...
  "___gxx_personality_v0", referenced from:
      -[DatamatrixWrapper getLuminanceSourceFromBuffer:imageBytes:] in libB4HVINScanner.a(DatamatrixWrapper.o)
      -[DatamatrixWrapper decode:withHints:] in libB4HVINScanner.a(DatamatrixWrapper.o)
      b4hscanner::Binarizer::~Binarizer() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BinaryBitmap::~BinaryBitmap() in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BinaryBitmap::getBlackRow(int, b4hscanner::Ref<b4hscanner::BitArray>) in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BinaryBitmap::getWidth() const in libB4HVINScanner.a(dm_scanner.o)
      b4hscanner::BinaryBitmap::getHeight() const in libB4HVINScanner.a(dm_scanner.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by nik123** [comment]
It seems like your XCode project is not set up properly. Ensure your app target has all required dependendies like it shown on screenshot. 
![xcode-screenshot](https://cloud.githubusercontent.com/assets/743376/12815095/c0f0a914-cb65-11e5-8107-14b39ddbd5d6.png)

**Comment by jasondenney** [comment]
Any chance at an update to this with bitcode enabled?  Still getting linker errors trying to rebuild our app that uses this scanner.
