### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by bbatie** [bees4honey/mobile_vin_scanner#20]
I would like to use your scanner in a current project, but while testing I got the error that it exceeded scans. Is it possible to license the scanner?

**Comment by nik123** [comment]
Yes, it is possible to license the scanner. In licensed version there would be no limit on number of scans. 

Please send us letter at vin@bees4honey.com for purchasing and licensing details.

**Comment by bbatie** [comment]
This is what I get when trying to install:
Brandons-Mac-mini-4: brandonbatie$ sudo npm install -g ionic
Password:
/Users/brandonbatie/.npm-packages/bin/ionic -> /Users/brandonbatie/.npm-packages/lib/node_modules/ionic/bin/ionic
ionic@2.1.18 /Users/brandonbatie/.npm-packages/lib/node_modules/ionic
└── @ionic/app-generators@0.0.3
Brandons-Mac-mini-4: brandonbatie$ ionic --v
1.7.15
