### ISSUE TITLE
QR Code Support

### ISSUE THREAD

**Issue by gregtzar** [bees4honey/mobile_vin_scanner#32]
Some newer vehicles have the VIN encoded in a QR code. The VIN scanner does scan the QR code but decodes in incorrectly. Are QR codes supported?

![qr-code-1](https://user-images.githubusercontent.com/412015/46253347-f09be380-c4ab-11e8-9e28-a5bd54f61772.png)

![qr-code-2](https://user-images.githubusercontent.com/412015/46253348-f5f92e00-c4ab-11e8-9f3e-6f78a1c7b3e3.png)

**Comment by nik123** [comment]
Unfrotunately QR codes are not yet supported in the library
